### PR TITLE
Create 32-bit int identifier for CPA compatibility

### PR DESCRIPTION
**Pull request by shntnu**

### CODE REVIEW

**Comment by gwaybio** [comment]
Once #108 is merged, I will review and resolve conflicts in this PR

**Comment by gwaybio** [comment]
@shntnu - no conflicts on this branch now after fd860831977105a8020393db410f68351cfec299

Merge at will! (I am working on release notes for new release)

**Comment by shntnu** [comment]
> I am working on release notes for new release

Great! Are you aware of this page https://github.com/cytomining/cytominer-database/wiki/Release ?

**Comment by gwaybio** [comment]
> Great! Are you aware of this page https://github.com/cytomining/cytominer-database/wiki/Release

I am now! Thanks for the pointer

**Comment by shntnu** [comment]
PS @gwaygenomics if you'd like to, you are welcome to make yourself the package maintainer :)

**Pull request merged**
